version: '3.8'

services:

  web:
    build:
      ./application
    container_name: web
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: always

  db:
    image: postgres:12.7
    container_name: db
    env_file:
      - .env
    ports:
      - '8001:5432'
    restart: always
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    command: redis-server --port "${REDIS_PORT}" --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - 6379:6379
    restart: always
